const customers = [
    {name: "mono", country: {name: "bangladesh"}, representative: {name: "Amy Elsner"}, status: "unqualified"},
    {name: "shumon", country: {name: "italy"}, representative: {name: "Anna Fali"}, status: "qualified"},
    {name: "sb", country: {name: "england"}, representative: {name: "Asiya Javayant"}, status: "new"},
    {name: "babu", country: {name: "Europe"}, representative: {name: "Bernardo Dominic"}, status: "negotiation"},
    {name: "ranjan", country: {name: "America"}, representative: {name: "Elwin Sharvill"}, status: "renewal"},
    {name: "mono", country: {name: "Asia"}, representative: {name: "Ioni Bowcher"}, status: "unqualified"},
    {name: "shumon", country: {name: "Africa"}, representative: {name: "Ivan Magalhaes"}, status: "qualified"},
    {name: "sb", country: {name: "Australia"}, representative: {name: "Onyama Limba"}, status: "new"},
    {name: "babu", country: {name: "India"}, representative: {name: "Stephen Shaw"}, status: "negotiation"},
    {name: "ranjan", country: {name: "China"}, representative: {name: "XuXue Feng"}, status: "renewal"},
]

const products = [
    {code: "a", name: "mono", category: "developer", quantity: 1},
    {code: "b", name: "mono", category: "developer", quantity: 2},
    {code: "c", name: "mono", category: "developer", quantity: 3},
    {code: "d", name: "mono", category: "developer", quantity: 4},
    {code: "e", name: "mono", category: "developer", quantity: 5},
    {code: "f", name: "mono", category: "developer", quantity: 6},
    {code: "g", name: "mono", category: "developer", quantity: 7},
    {code: "h", name: "mono", category: "developer", quantity: 8},
    {code: "i", name: "mono", category: "developer", quantity: 9},
    {code: "j", name: "mono", category: "developer", quantity: 10},
    {code: "k", name: "mono", category: "developer", quantity: 11},
    {code: "l", name: "mono", category: "developer", quantity: 12},
    {code: "m", name: "mono", category: "developer", quantity: 13},
    {code: "n", name: "mono", category: "developer", quantity: 14},
    {code: "o", name: "mono", category: "developer", quantity: 15},
    {code: "p", name: "mono", category: "developer", quantity: 16},
    {code: "q", name: "mono", category: "developer", quantity: 17},
    {code: "r", name: "mono", category: "developer", quantity: 18},
    {code: "s", name: "mono", category: "developer", quantity: 19},
    {code: "t", name: "mono", category: "developer", quantity: 20},
    {code: "u", name: "mono", category: "developer", quantity: 21},
    {code: "v", name: "mono", category: "developer", quantity: 22},
    {code: "w", name: "mono", category: "developer", quantity: 23},
    {code: "v", name: "mono", category: "developer", quantity: 24},
    {code: "y", name: "mono", category: "developer", quantity: 25},
    {code: "z", name: "mono", category: "developer", quantity: 26},
]

const representatives = [
    { name: 'Amy Elsner', image: 'amyelsner.png' },
    { name: 'Anna Fali', image: 'annafali.png' },
    { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
    { name: 'Bernardo Dominic', image: 'bernardodominic.png' },
    { name: 'Elwin Sharvill', image: 'elwinsharvill.png' },
    { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
    { name: 'Ivan Magalhaes', image: 'ivanmagalhaes.png' },
    { name: 'Onyama Limba', image: 'onyamalimba.png' },
    { name: 'Stephen Shaw', image: 'stephenshaw.png' },
    { name: 'XuXue Feng', image: 'xuxuefeng.png' }
]
export {customers, products, representatives};